# Generated by Django 3.2.18 on 2023-04-04 20:26

import api_pandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(default=api_pandas.models.next_available_id, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('other_fields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
