# Generated by Django 3.2.18 on 2023-04-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('industry', models.CharField(max_length=255)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_fields', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
