# Generated by Django 3.2.18 on 2023-04-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_pandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
    ]
