# Generated by Django 3.2.18 on 2023-04-04 20:08

import api_pandas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pandas', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(default=api_pandas.models.next_available_id, primary_key=True, serialize=False),
        ),
    ]
